baseURL = "https://rshsyari.github.io/"
relativeURLs = true
canonifyURLs = true
languageCode = 'en-us'
title = 'rshsyari'
theme = "gokarna"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  avatarAltText = "avatar"
  avatarSize = "size-s"
  avatarURL = "/images/penguin.jpg"

  env = "production"
  homeInfoParams = { Title = "rshsyari" }
  mainSections = ["posts"] 

  footer = "rshsyari"
  description = "Indonesian government sucks"
  metaKeywords = ["blog", "gokarna", "hugo"]
  showBackToTopButton = true
  homeLayout = "list"
  numberPostsOnHomePage = 6
  showPostsOnHomePage = "popular" 



  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/rshsyari"},
    {name = "github", url = "https://github.com/rshsyari"},
    {name = "instagram", url = "https://instagram.com/rshsyari"},
    {name = "email", url = "mailto:rshsyari@gmail.com"}
  ]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

[[headers]]
  for = '/**'
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://trusted.cdn.com; object-src 'none'; base-uri 'self'; form-action 'self'; style-src 'self' https://trusted.cdn.com; frame-ancestors 'none'; upgrade-insecure-requests;"
    Referrer-Policy = 'strict-origin-when-cross-origin'
    X-Content-Type-Options = 'nosniff'
    X-Frame-Options = 'DENY'
    X-XSS-Protection = '1; mode=block'